MOCK_FIND_NEWS = [
  {'url': ('https://blog.betrybe.com/tecnologia'
           '/jogos-iniciantes-aprender-programar/'),
   'title': '10 jogos para iniciantes aprenderem a programar!',
   'timestamp': '22/05/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 12,
   'summary': 'A programação é o momento. De uns anos para cá, cada vez...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/endless-os/',
   'title': 'Endless OS: por que vale a pena usar esse sistema',
   'timestamp': '18/05/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 12,
   'summary': 'Os computadores com uma configuração mais básica e preço ma...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/carreira/trybetalks-nubank-vitor-olivier/',
   'title': 'TrybeTalks – CTO do Nubank revela as habilidades de sucesso',
   'timestamp': '15/05/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 6,
   'summary': 'Vitor Olivier, o CTO do Nubank, revela quais são as habili...',
   'category': 'Carreira'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/site-responsivo/',
   'title': 'Site responsivo: o que é e 10 dicas para aplicar',
   'timestamp': '10/05/2023',
   'writer': 'Lucas Marchiori',
   'reading_time': 11,
   'summary': 'Com o avanço da tecnologia, grande parte das pessoas...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/modelo-as-a-service/',
   'title': 'SaaS, GaaS, IaaS, DaaS, PaaS: entenda o modelo as a service',
   'timestamp': '27/04/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 14,
   'summary': 'Você sabe o que é computação em nuvem? Se você já...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/armazenamento-em-nuvem/',
   'title': 'Armazenamento em nuvem: o que é e quais os 7 melhores?',
   'timestamp': '20/04/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 12,
   'summary': 'Em algum momento você já se perguntou se é seguro...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/componentizacao-tudo-sobre/',
   'title': 'Componentização: o que é, por que usar e exemplo na prática!',
   'timestamp': '17/04/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 10,
   'summary': 'Se você é uma pessoa programadora, desenvolvedora ou...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/10-navegadores-leves/',
   'title': '10 navegadores leves, rápidos e seguros para PC fraco!',
   'timestamp': '13/04/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 9,
   'summary': 'Dá pra se imaginar sem internet? É por meio dela que...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/cabos-de-rede/',
   'title': 'Cabos de rede: o que são, quais os tipos e como crimpar?',
   'timestamp': '10/04/2023',
   'writer': 'Dayane Arena dos Santos',
   'reading_time': 9,
   'summary': 'Os cabos de rede são itens extremamente necessários para...',
   'category': 'Tecnologia'
   },
  {'url': ('https://blog.betrybe.com/desenvolvimento-web/'
           'estruturas-de-repeticao/'),
   'title': 'Estruturas de repetição: quais as 4 principais e quando usá-las?',
   'timestamp': '05/04/2023',
   'writer': 'Vinicius Martins',
   'reading_time': 5,
   'summary': 'As estruturas de repetição estão muito presentes na vida...',
   'category': 'Desenvolvimento Web'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/website-development/',
   'title': ('Website development: o que é, o que'
             ' faz e salário! O guia inicial!'),
   'timestamp': '31/03/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 13,
   'summary': 'O Website development pode ser encontrado no mercado de...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/code-review/',
   'title': 'Code Review: como virar um caçador de bugs com 15 dicas',
   'timestamp': '22/03/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 11,
   'summary': 'Manter a consistência do código de um projeto e identifica...',
   'category': 'Tecnologia'
   },
  {'url': ('https://blog.betrybe.com/desenvolvimento-web/'
           'versionamento-software-codigo/'),
   'title': 'Versionamento de software e de código: o que é e como fazer?',
   'timestamp': '16/03/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 12,
   'summary': 'Gerar muitas mudanças em documentos, códigos ou softwares...',
   'category': 'Desenvolvimento Web'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/metadados-tudo-sobre/',
   'title': 'Metadados: o que são, 20 exemplos e como gerenciar?',
   'timestamp': '14/03/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 7,
   'summary': 'Todos os dias, milhares de dados são produzidos, compart...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/desenvolvimento-web/angular-cli/',
   'title': 'Angular CLI: como usar essa interface de linha de comando?',
   'timestamp': '08/03/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 6,
   'summary': 'Criar um projeto web com todas as estruturas de pastas...',
   'category': 'Desenvolvimento Web'
   },
  {'url': 'https://blog.betrybe.com/linguagem-de-programacao/o-que-e-array/',
   'title': 'O que é array, para que serve e como fazer?',
   'timestamp': '06/03/2023',
   'writer': 'Gleiciane Kelly',
   'reading_time': 5,
   'summary': 'Array é uma estrutura que comporta uma coleção de da...',
   'category': 'Linguagem de Programação'
   },
  {'url': ('https://blog.betrybe.com/tecnologia/'
           'usabilidade-no-desenvolvimento-de-software/'),
   'title': 'Usabilidade no Desenvolvimento de software e UX: como funciona?',
   'timestamp': '01/03/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 11,
   'summary': 'Você já passou pela frustração de tentar usar um aplicativ...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/antivirus-android/',
   'title': 'Antivírus Android: conheça os 10 melhores e saiba por que usar!',
   'timestamp': '27/02/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 10,
   'summary': 'Com o grande crescimento da tecnologia e das tecnologia...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/tipos-de-firewall/',
   'title': ('Conheça os 11 tipos de firewall, '
             'saiba como funcionam e qual usar'),
   'timestamp': '22/02/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 9,
   'summary': 'O surgimento dos tipos de firewall foi um avança...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/protocolo-tcp-ip/',
   'title': 'Protocolo TCP/IP: o que é e exemplos de como funciona',
   'timestamp': '17/02/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 9,
   'summary': 'A todo o instante diversos dados trafegam pela rede: seja ...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/programacao-em-arduino/',
   'title': 'Programação em Arduino para iniciantes em 11 passos!',
   'timestamp': '14/02/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 14,
   'summary': 'Você sabia que com a utilização de um arduino é poss...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/sistema-operacional-windows/',
   'title': 'Sistema Operacional Windows: versões, dicas e como instalar?',
   'timestamp': '06/02/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 18,
   'summary': 'É fato que todo computador necessita de um sistema o...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/exemplos-de-algoritmos/',
   'title': '5 exemplos de algoritmos na vida real e na computação',
   'timestamp': '03/02/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 5,
   'summary': 'Quando falamos de algoritmos, pensamos em matemática...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/carreira/trybetalks-gaules/',
   'title': 'TrybeTalks — Gaules: os ensinamentos de um streamer do Brasil',
   'timestamp': '30/01/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 9,
   'summary': 'Gaules, uma das maiores personalidades do mundo de espor...',
   'category': 'Carreira'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/next-js/',
   'title': 'Next JS: o que é, para que serve e por que usar?',
   'timestamp': '27/01/2023',
   'writer': 'Lucas Marchiori',
   'reading_time': 13,
   'summary': 'Conhecer as principais tecnologias do mercado, biblio...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/hardware-software-diferencas/',
   'title': 'Hardware e software: o que são e quais as diferenças?',
   'timestamp': '26/01/2023',
   'writer': 'Lucas Marchiori',
   'reading_time': 8,
   'summary': 'Hardware e software são conceitos muito valiosos pa...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/firewall-tudo-sobre/',
   'title': 'Firewall: o que é, como funciona, 11 tipos e como configurar',
   'timestamp': '23/01/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 10,
   'summary': 'Se você utiliza Windows já deve ter se deparado com...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/operadores-boleanos/',
   'title': 'Operadores booleanos: 3 exemplos para usar em pesquisas',
   'timestamp': '18/01/2023',
   'writer': 'Gleiciane Kelly',
   'reading_time': 4,
   'summary': 'Os operadores booleanos permitem buscas com r...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/mark-zuckerberg-metaverso/',
   'title': 'Mark Zuckerberg é o criador do Metaverso?',
   'timestamp': '16/01/2023',
   'writer': 'Lucas Custódio',
   'reading_time': 9,
   'summary': 'Mark Zuckerberg revolucionou a forma como nos re...',
   'category': 'Tecnologia'
   },
  {'url': 'https://blog.betrybe.com/tecnologia/software-livre/',
   'title': ('Software livre: o que é, características, '
             'curiosidades e diferenças!'),
   'timestamp': '13/01/2023',
   'writer': 'Cairo Noleto',
   'reading_time': 9,
   'summary': 'Quando falamos sobre software livre, estamos fala...',
   'category': 'Tecnologia'
   },
]
